import { ProvinceName } from "./province-name.model";
import { Province } from "./province.model";

export const getProvincesDeck = (): Province[] => [
    new Province(
        ProvinceName.AEGYPTUS,
        false,
        ['Alexandrine War'],
        3,
        7,
        '1d6 + 7',
        '1d6 + 3',
        60,
        8,
        13,
        'Created by: Egyptian Annexation (Always Developed)',
        3,
        7,
        '1d6 + 7',
        '1d6 + 3',
        60,
        8,
        13,
        'Created by: Egyptian Annexation (Always Developed)',
        true
    ),
    new Province(
        ProvinceName.AFRICA,
        false,
        ['Jugurthine War'],
        3,
        5,
        '1d6 - 1',
        '2d6 - 4',
        20,
        5,
        3,
        'Created by: 3rd Punic War',
        4,
        5,
        '1d6 + 3',
        '1d6 + 1',
        30,
        10,
        5
    ),
    new Province(
        ProvinceName.ASIA,
        false,
        ['Mithridatic Wars', 'Parthian War', 'Syrian War'],
        6,
        5,
        '1d6 + 2',
        '2d6 - 3',
        35,
        10,
        10,
        'Created by: Pergamon Bequest',
        6,
        5,
        '1d6 + 6',
        '2d6 + 3',
        50,
        10,
        10
    ),
    new Province(
        ProvinceName.BITHYNIA,
        false,
        ['Mithridatic Wars', 'Parthian War', 'Syrian War', '1st Cilician Pirates'],
        2,
        5,
        '1d6 - 4',
        '1d6 - 2',
        10,
        1,
        3,
        'Created by: Bithynian Bequest',
        4,
        5,
        '1d6 + 2',
        '1d6 + 2',
        30,
        10,
        5,
        'Developed by: 1d6 ≥ 6 or 3rd Mithridatic War'
    ),
    new Province(
        ProvinceName.CILICIA_ET_CYPRUS,
        false,
        ['Parthian War', '2nd Cilician Pirates'],
        2,
        5,
        '1d6 - 4',
        '-1d6',
        10,
        0,
        3,
        'Created by: 1st Cilician Pirates',
        3,
        5,
        '1d6',
        '-1d6 + 3',
        20,
        1,
        5
    ),
    new Province(
        ProvinceName.CRETA_ET_CYRENAICA,
        true,
        ['2nd Cilician Pirates'],
        1,
        5,
        '1d6 - 1',
        '1d6 - 2',
        15,
        5,
        5,
        'Created by: Bequest or 2nd Cilician Pirates',
        2,
        5,
        '1d6 + 1',
        '1d6 + 2',
        20,
        10,
        5
    ),
    new Province(
        ProvinceName.GALLIA_CISALPINA,
        true,
        ['Gallic Wars', 'Germanic Migrations', '2nd Punic War'],
        1,
        0,
        '1d6 - 1',
        '1d6 - 1',
        15,
        5,
        0,
        'Created by: 1st Gallic War',
        2,
        0,
        '1d6 + 3',
        '2d6 - 1',
        20,
        10,
        0
    ),
    new Province(
        ProvinceName.GALLIA_NARBONENSIS,
        false,
        ['Gallic Wars', '2nd Punic War'],
        1,
        0,
        '1d6 - 3',
        '1d6 - 3',
        10,
        5,
        0,
        'Created by: Germanic Migrations',
        2,
        0,
        '1d6 + 1',
        '1d6 + 1',
        20,
        10,
        0
    ),
    new Province(
        ProvinceName.GALLIA_TRANSALPINA,
        true,
        ['Gallic Wars', 'Germanic Migrations'],
        3,
        0,
        '1d6 - 4',
        '1d6 - 5',
        10,
        5,
        0,
        'Created by: 2nd/3rd Gallic War',
        6,
        0,
        '1d6',
        '1d6 + 1',
        20,
        10,
        0
    ),
    new Province(
        ProvinceName.HISPANIA_CITERIOR,
        true,
        ['Spanish Revolts'],
        1,
        0,
        '1d6 - 2',
        '-1d6 + 1',
        10,
        5,
        0,
        'Created by: 2nd Punic War',
        2,
        0,
        '1d6 + 2',
        '1d6 + 1',
        15,
        10,
        0
    ),
    new Province(
        ProvinceName.HISPANIA_ULTERIOR,
        true,
        ['Lusitanian War', 'Sertorian Revolt'],
        2,
        0,
        '1d6 - 3',
        '-1d6 - 1',
        10,
        5,
        0,
        'Created by: 2nd Punic War',
        4,
        0,
        '1d6 + 1',
        '1d6 - 1',
        20,
        10,
        0
    ),
    new Province(
        ProvinceName.ILLYRICUM,
        true,
        ['Macedonian Wars', 'Germanic Migrations'],
        2,
        0,
        '1d6 - 3',
        '-1d6 - 1',
        5,
        5,
        0,
        'Created by: both Illyrian Wars',
        4,
        0,
        '1d6',
        '1d6',
        15,
        10,
        0
    ),
    new Province(
        ProvinceName.MACEDONIA,
        true,
        ['Macedonian Wars', 'Illyrian Wars', 'Syrian War', '1st Mithridatic War'],
        5,
        5,
        '1d6 + 1',
        '2d6 - 2',
        30,
        10,
        10,
        'Created by: 4th Macedonian War',
        5,
        5,
        '2d6 - 1',
        '2d6 + 2',
        40,
        10,
        10
    ),
    new Province(
        ProvinceName.SARDINIA_ET_CORSICA,
        false,
        ['1st Cilician Pirates'],
        0,
        0,
        '1d6 - 5',
        '-1d6 - 1',
        5,
        0,
        3,
        'Created by: 1st Punic War',
        1,
        0,
        '1d6 - 1',
        '-1d6 + 1',
        10,
        1,
        5
    ),
    new Province(
        ProvinceName.SICILIA,
        false,
        ['Sicilian Slave Revolt'],
        2,
        0,
        '1d6',
        '2d6 - 2',
        30,
        10,
        5,
        'Created by: 1st Punic War',
        2,
        0,
        '1d6 + 4',
        '1d6 + 2',
        40,
        10,
        5
    ),
    new Province(
        ProvinceName.SYRIA,
        false,
        ['Parthian War', 'Mithridatic Wars'],
        4,
        5,
        '1d6 - 1',
        '1d6',
        20,
        10,
        10,
        'Created by: 3rd Mithridatic War',
        4,
        5,
        '1d6 + 3',
        '1d6',
        30,
        10,
        10
    )
];